config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "posts#index"
  resources :posts do
    resources :comments
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  has_rich_text :comment
  validates :title, presence: true
  validates :comment, presence: true
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, presence: true
  validates :body, presence: true
  has_many :comments
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_params, only: %i(create destroy)

  def create
    @comment = @post.comments.create(params[:comment].permit(:title, :comment))
    redirect_to post_path(@post)
  end

  def destroy
    @comment = @post.comments.find(params[:id])
    @comment.destroy
    redirect_to post_path(@post)
  end

  private

  def set_params
    @post = Post.find(params[:post_id])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[show edit update destroy]
  
  def index
    @posts = Post.all
    @post = Post.new
  end

  def show
  end

  def new
    @post = Post.new
  end

  def create
    post = Post.create(post_params)

    redirect_to posts_path
  end

  def edit
  end

  def update
    @post.update(post_params)
    redirect_to posts_path
  end

  def destroy
    @post.destroy
    redirect_to posts_path
  end

  private

  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/comments/_comment.html.erb
<h4><%= comment.title %></h4>
<p><%= comment.comment %></p>
<% if comment.title %>
  <%= button_to "Delete", [comment.post, comment], method: :delete, class: "btn btn-danger" %>
<% end %>

app/views/comments/_form.html.erb
<%= form_with model: [@post, @post.comments.build] do |f| %>
 <%= f.label :title, "Title" %>
 <p><%= f.text_field :title %></p>
 <%= f.label :comment, "Comment" %>
 <p><%= f.rich_text_area :comment %></p>
 <%= f.submit "Save Comment", class: "btn btn-success" %>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-dark bg-dark navbar-expand-lg">
  <div class="container-fluid">
    <%= link_to "Blog", posts_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarScroll" aria-controls="navbarScroll" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarScroll">
      <ul class="navbar-nav me-auto my-2 my-lg-0 navbar-nav-scroll" style="--bs-scroll-height: 100px;">
        <li class="nav-item">
          <%= link_to "Posts", posts_path, class: "nav-link active" %>
        </li>
      </ul>
      <ul class="navbar-nav me-right my-2">
      <% if user_signed_in? %>
        <li class="nav-item account-name">
          <%= link_to current_user.email, edit_user_registration_path %>
        </li>
        <li class="nav-item">
          <%= button_to "Sign Out", destroy_user_session_path, class: "btn btn-warning mx-2", method: :delete %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Registration", new_user_registration_path, class: "btn btn-primary mx-2" %>
        </li>
        <li class="nav-item">
          <%= link_to "Sign In", new_user_session_path, class: "btn btn-outline-primary mx-2" %>
        </li>
      <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HomeBlog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "layouts/navbar" %>
    <p><%= flash[:notice] %></p>
    <p><%= flash[:alert] %></p>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with model: post do |f| %>
  <p><%= f.label :title, "Title of Post"%></p>
  <p><%= f.text_field :title %></p>
  <p><%= f.label :body, "Text of Post" %></p>
  <p><%= f.text_area :body %></p>
  <p><%= f.submit "Save Post", class: "btn btn-success"%></p>
<% end %>

app/views/posts/_post.html.erb
<div class="post">
  <h3><%= link_to post.title, post_path(post) %></h3>
  <p><%= post.body %></p>
<div>

app/views/posts/edit.html.erb
<h2>Edit Post</h2>
<%= render 'form', post: @post %>
<%= link_to 'Back', :back, class: "btn btn-outline-primary" %>

app/views/posts/index.html.erb
<h1>Posts</h1>
<%= render 'form', post: @post %>
<% @posts.each do |post|%>
  <%= render post %>
  <% if user_signed_in? %>
    <div class="links-post">
      <%= link_to "Edit", edit_post_path(post), class: "btn btn-outline-primary"%>
      <%= button_to "Delete", post_path(post), method: :delete, class: "btn btn-danger" %>
    </div>
  <% end %>
<% end %>
</div>

app/views/posts/show.html.erb
<%= render 'post', post: @post %>
<div class="links-post">
<%= link_to 'Back', posts_path, class: "btn btn-primary" %>
<% if user_signed_in? %>
  <%= link_to "Edit", edit_post_path(@post), class: "btn btn-outline-primary" %>
  <%= button_to "Delete", post_path(@post), method: :delete, class: "btn btn-danger" %>
</div>
  <section class="comments">
    <div class="comment-form">
      <h3>Leave a reply</h3>
      <%= render 'comments/form' %>
    </div>
    <h2>Comments: <%= @post.comments.count %></h2>
    <div class="comments-body">
        <%= render @post.comments %>
    </div>
  </section>
<% end %>